LAPACK_DOUBLE_SRC =  dbbcsd.f  dbdsdc.f  dbdsqr.f  dbdsvdx.f ddisna.f  dgbbrd.f\
                     dgbcon.f  dgbequ.f  dgbequb.f dgbrfs.f  dgbrfsx.f dgbsv.f\
                     dgbsvx.f  dgbsvxx.f dgbtf2.f  dgbtrf.f  dgbtrs.f  dgebak.f\
                     dgebal.f  dgebd2.f  dgebrd.f  dgecon.f  dgeequ.f  dgeequb.f\
                     dgees.f   dgeesx.f  dgeev.f   dgeevx.f  dgehd2.f  dgehrd.f\
                     dgejsv.f  dgelq.f   dgelq2.f  dgelqf.f  dgelqt.f  dgelqt3.f\
                     dgels.f   dgelsd.f  dgelss.f  dgelsy.f  dgemlq.f  dgemlqt.f\
                     dgemqr.f  dgemqrt.f dgeql2.f  dgeqlf.f  dgeqp3.f  dgeqr.f\
                     dgeqr2.f  dgeqr2p.f dgeqrf.f  dgeqrfp.f dgeqrt.f dgeqrt2.f\
                     dgeqrt3.f dgerfs.f  dgerfsx.f dgerq2.f  dgerqf.f dgesc2.f\
                     dgesdd.f dgesv.f dgesvd.f dgesvdx.f dgesvj.f dgesvx.f\
                     dgesvxx.f dgetc2.f dgetf2.f dgetrf.f dgetrf2.f dgetri.f\
                     dgetrs.f dgetsls.f dggbak.f dggbal.f dgges.f dgges3.f\
                     dggesx.f dggev.f dggev3.f dggevx.f dggglm.f dgghd3.f\
                     dgghrd.f dgglse.f dggqrf.f dggrqf.f dggsvd3.f dggsvp3.f\
                     dgsvj0.f dgsvj1.f dgtcon.f dgtrfs.f dgtsv.f dgtsvx.f\
                     dgttrf.f dgttrs.f dgtts2.f dhgeqz.f dhsein.f dhseqr.f\
                     disnan.f dla_gbamv.f dla_gbrcond.f dla_gbrfsx_extended.f\
                     dla_gbrpvgrw.f dla_geamv.f dla_gercond.f dla_gerfsx_extended.f\
                     dla_gerpvgrw.f dla_lin_berr.f dla_porcond.f dla_porfsx_extended.f\
                     dla_porpvgrw.f dla_syamv.f dla_syrcond.f dla_syrfsx_extended.f\
                     dla_syrpvgrw.f dla_wwaddw.f dlabad.f dlabrd.f dlacn2.f dlacon.f\
                     dlacpy.f dladiv.f dlae2.f dlaebz.f dlaed0.f dlaed1.f\
                     dlaed2.f dlaed3.f dlaed4.f dlaed5.f dlaed6.f dlaed7.f\
                     dlaed8.f dlaed9.f dlaeda.f dlaein.f dlaev2.f dlaexc.f\
                     dlag2.f dlag2s.f dlags2.f dlagtf.f dlagtm.f dlagts.f\
                     dlagv2.f dlahqr.f dlahr2.f dlaic1.f dlaisnan.f dlaln2.f\
                     dlals0.f dlalsa.f dlalsd.f dlamch.f dlamrg.f dlamswlq.f\
                     dlamtsqr.f dlaneg.f dlangb.f dlange.f dlangt.f dlanhs.f\
                     dlansb.f dlansf.f dlansp.f dlanst.f dlansy.f dlantb.f\
                     dlantp.f dlantr.f dlanv2.f dlapll.f dlapmr.f dlapmt.f\
                     dlapy2.f dlapy3.f dlaqgb.f dlaqge.f dlaqp2.f dlaqps.f\
                     dlaqr0.f dlaqr1.f dlaqr2.f dlaqr3.f dlaqr4.f dlaqr5.f\
                     dlaqsb.f dlaqsp.f dlaqsy.f dlaqtr.f dlar1v.f dlar2v.f\
                     dlarf.f dlarfb.f dlarfg.f dlarfgp.f dlarft.f dlarfx.f\
                     dlarfy.f dlargv.f dlarnv.f dlarra.f dlarrb.f dlarrc.f\
                     dlarrd.f dlarre.f dlarrf.f dlarrj.f dlarrk.f dlarrr.f\
                     dlarrv.f dlarscl2.f dlartg.f dlartgp.f dlartgs.f dlartv.f\
                     dlaruv.f dlarz.f dlarzb.f dlarzt.f dlas2.f dlascl.f dlascl2.f\
                     dlasd0.f dlasd1.f dlasd2.f dlasd3.f dlasd4.f dlasd5.f\
                     dlasd6.f dlasd7.f dlasd8.f dlasda.f dlasdq.f dlasdt.f\
                     dlaset.f dlasq1.f dlasq2.f dlasq3.f dlasq4.f dlasq5.f\
                     dlasq6.f dlasr.f dlasrt.f dlassq.f dlasv2.f dlaswlq.f\
                     dlaswp.f dlasy2.f dlasyf.f dlasyf_aa.f dlasyf_rk.f\
                     dlasyf_rook.f dlat2s.f dlatbs.f dlatdf.f dlatps.f dlatrd.f\
                     dlatrs.f dlatrz.f dlatsqr.f dlauu2.f dlauum.f dopgtr.f\
                     dopmtr.f dorbdb.f dorbdb1.f dorbdb2.f dorbdb3.f dorbdb4.f\
                     dorbdb5.f dorbdb6.f dorcsd.f dorcsd2by1.f dorg2l.f\
                     dorg2r.f dorgbr.f dorghr.f dorgl2.f dorglq.f dorgql.f\
                     dorgqr.f dorgr2.f dorgrq.f dorgtr.f dorm22.f dorm2l.f\
                     dorm2r.f dormbr.f dormhr.f dorml2.f dormlq.f dormql.f\
                     dormqr.f dormr2.f dormr3.f dormrq.f dormrz.f dormtr.f\
                     dpbcon.f dpbequ.f dpbrfs.f dpbstf.f dpbsv.f dpbsvx.f\
                     dpbtf2.f dpbtrf.f dpbtrs.f dpftrf.f dpftri.f dpftrs.f\
                     dpocon.f dpoequ.f dpoequb.f dporfs.f dporfsx.f dposv.f\
                     dposvx.f dposvxx.f dpotf2.f dpotrf.f dpotrf2.f dpotri.f\
                     dpotrs.f dppcon.f dppequ.f dpprfs.f dppsv.f dppsvx.f\
                     dpptrf.f dpptri.f dpptrs.f dpstf2.f dpstrf.f dptcon.f\
                     dpteqr.f dptrfs.f dptsv.f dptsvx.f dpttrf.f dpttrs.f\
                     dptts2.f drscl.f dsb2st_kernels.f dsbev.f dsbev_2stage.f\
                     dsbevd.f dsbevd_2stage.f dsbevx.f dsbevx_2stage.f\
                     dsbgst.f dsbgv.f dsbgvd.f dsbgvx.f dsbtrd.f dsfrk.f\
                     dsgesv.f dspcon.f dspev.f dspevd.f dspevx.f dspgst.f\
                     dspgv.f dspgvd.f dspgvx.f dsposv.f dsprfs.f dspsv.f\
                     dspsvx.f dsptrd.f dsptrf.f dsptri.f dsptrs.f dstebz.f\
                     dstedc.f dstegr.f dstein.f dstemr.f dsteqr.f dsterf.f\
                     dstev.f dstevd.f dstevr.f dstevx.f dsycon.f dsycon_3.f\
                     dsycon_rook.f dsyconv.f dsyconvf.f dsyconvf_rook.f\
                     dsyequb.f dsyev.f dsyev_2stage.f dsyevd.f dsyevd_2stage.f\
                     dsyevr.f dsyevr_2stage.f dsyevx.f dsyevx_2stage.f dsygs2.f\
                     dsygst.f dsygv.f dsygv_2stage.f dsygvd.f dsygvx.f dsyrfs.f\
                     dsyrfsx.f dsysv.f dsysv_aa.f dsysv_aa_2stage.f dsysv_rk.f\
                     dsysv_rook.f dsysvx.f dsysvxx.f dsyswapr.f dsytd2.f\
                     dsytf2.f dsytf2_rk.f dsytf2_rook.f dsytrd.f dsytrd_2stage.f\
                     dsytrf.f dsytrf_aa.f\
                     dsytrf_aa_2stage.f dsytrf_rk.f dsytrf_rook.f dsytri.f\
                     dsytri2.f dsytri2x.f dsytri_3.f dsytri_3x.f dsytri_rook.f\
                     dsytrs.f dsytrs2.f dsytrs_3.f dsytrs_aa.f dsytrs_aa_2stage.f\
                     dsytrs_rook.f dtbcon.f dtbrfs.f dtbtrs.f dtfsm.f dtftri.f\
                     dtfttp.f dtfttr.f dtgevc.f dtgex2.f dtgexc.f dtgsen.f\
                     dtgsja.f dtgsna.f dtgsy2.f dtgsyl.f dtpcon.f dtplqt.f\
                     dtplqt2.f dtpmlqt.f dtpmqrt.f dtpqrt.f dtpqrt2.f dtprfb.f\
                     dtprfs.f dtptri.f dtptrs.f dtpttf.f dtpttr.f dtrcon.f\
                     dtrevc.f dtrevc3.f dtrexc.f dtrrfs.f dtrsen.f dtrsna.f\
                     dtrsyl.f dtrti2.f dtrtri.f dtrtrs.f dtrttf.f dtrttp.f\
                     dtzrzf.f dzsum1.f icmax1.f ieeeck.f ilaclc.f ilaclr.f\
                     iladiag.f iladlc.f iladlr.f ilaenv.f ilaenv2stage.f\
                     ilaprec.f ilaslc.f ilaslr.f ilatrans.f ilauplo.f ilazlc.f\
                     ilazlr.f iparmq.f izmax1.f 
                     
                     
LAPACK_DOUBLE_SRCF = iparam2stage.F  dsytrd_sb2st.F dsytrd_sy2sb.F