LAPACK_COMPLEX_SRC = dlamch.f icmax1.f ieeeck.f ilaclc.f ilaclr.f iladiag.f\
                     iladlc.f iladlr.f ilaenv.f ilaenv2stage.f ilaprec.f\
                     ilaslc.f ilaslr.f ilatrans.f ilauplo.f ilazlc.f ilazlr.f\
                     iparmq.f izmax1.f zbbcsd.f zbdsqr.f zcgesv.f zcposv.f\
                     zdrscl.f zgbbrd.f zgbcon.f zgbequ.f zgbequb.f zgbrfs.f\
                     zgbrfsx.f zgbsv.f zgbsvx.f zgbsvxx.f zgbtf2.f zgbtrf.f\
                     zgbtrs.f zgebak.f zgebal.f zgebd2.f zgebrd.f zgecon.f\
                     zgeequ.f zgeequb.f zgees.f zgeesx.f zgeev.f zgeevx.f\
                     zgehd2.f zgehrd.f zgejsv.f zgelq.f zgelq2.f zgelqf.f\
                     zgelqt.f zgelqt3.f zgels.f zgelsd.f zgelss.f zgelsy.f\
                     zgemlq.f zgemlqt.f zgemqr.f zgemqrt.f zgeql2.f zgeqlf.f\
                     zgeqp3.f zgeqr.f zgeqr2.f zgeqr2p.f zgeqrf.f zgeqrfp.f\
                     zgeqrt.f zgeqrt2.f zgeqrt3.f zgerfs.f zgerfsx.f zgerq2.f\
                     zgerqf.f zgesc2.f zgesdd.f zgesv.f zgesvd.f zgesvdx.f\
                     zgesvj.f zgesvx.f zgesvxx.f zgetc2.f zgetf2.f zgetrf.f\
                     zgetrf2.f zgetri.f zgetrs.f zgetsls.f zggbak.f zggbal.f\
                     zgges.f zgges3.f zggesx.f zggev.f zggev3.f zggevx.f\
                     zggglm.f zgghd3.f zgghrd.f zgglse.f zggqrf.f zggrqf.f\
                     zggsvd3.f zggsvp3.f zgsvj0.f zgsvj1.f zgtcon.f zgtrfs.f\
                     zgtsv.f zgtsvx.f zgttrf.f zgttrs.f zgtts2.f\
                     zhb2st_kernels.f zhbev.f zhbev_2stage.f zhbevd.f\
                     zhbevd_2stage.f zhbevx.f zhbevx_2stage.f zhbgst.f zhbgv.f\
                     zhbgvd.f zhbgvx.f zhbtrd.f zhecon.f zhecon_3.f\
                     zhecon_rook.f zheequb.f zheev.f zheev_2stage.f zheevd.f\
                     zheevd_2stage.f zheevr.f zheevr_2stage.f zheevx.f\
                     zheevx_2stage.f zhegs2.f zhegst.f zhegv.f zhegv_2stage.f\
                     zhegvd.f zhegvx.f zherfs.f zherfsx.f zhesv.f zhesv_aa.f\
                     zhesv_aa_2stage.f zhesv_rk.f zhesv_rook.f zhesvx.f\
                     zhesvxx.f zheswapr.f zhetd2.f zhetf2.f zhetf2_rk.f\
                     zhetf2_rook.f zhetrd.f zhetrd_2stage.f zhetrd_he2hb.f\
                     zhetrf.f zhetrf_aa.f zhetrf_aa_2stage.f zhetrf_rk.f\
                     zhetrf_rook.f zhetri.f zhetri2.f zhetri2x.f zhetri_3.f\
                     zhetri_3x.f zhetri_rook.f zhetrs.f zhetrs2.f zhetrs_3.f\
                     zhetrs_aa.f zhetrs_aa_2stage.f zhetrs_rook.f zhfrk.f\
                     zhgeqz.f zhpcon.f zhpev.f zhpevd.f zhpevx.f zhpgst.f\
                     zhpgv.f zhpgvd.f zhpgvx.f zhprfs.f zhpsv.f zhpsvx.f\
                     zhptrd.f zhptrf.f zhptri.f zhptrs.f zhsein.f zhseqr.f\
                     zla_gbamv.f zla_gbrcond_c.f zla_gbrcond_x.f\
                     zla_gbrfsx_extended.f zla_gbrpvgrw.f zla_geamv.f\
                     zla_gercond_c.f zla_gercond_x.f zla_gerfsx_extended.f\
                     zla_gerpvgrw.f zla_heamv.f zla_hercond_c.f zla_hercond_x.f\
                     zla_herfsx_extended.f zla_herpvgrw.f zla_lin_berr.f\
                     zla_porcond_c.f zla_porcond_x.f zla_porfsx_extended.f\
                     zla_porpvgrw.f zla_syamv.f zla_syrcond_c.f zla_syrcond_x.f\
                     zla_syrfsx_extended.f zla_syrpvgrw.f zla_wwaddw.f zlabrd.f\
                     zlacgv.f zlacn2.f zlacon.f zlacp2.f zlacpy.f zlacrm.f\
                     zlacrt.f zladiv.f zlaed0.f zlaed7.f zlaed8.f zlaein.f\
                     zlaesy.f zlaev2.f zlag2c.f zlags2.f zlagtm.f zlahef.f\
                     zlahef_aa.f zlahef_rk.f zlahef_rook.f zlahqr.f zlahr2.f\
                     zlaic1.f zlals0.f zlalsa.f zlalsd.f zlamswlq.f zlamtsqr.f\
                     zlangb.f zlange.f zlangt.f zlanhb.f zlanhe.f zlanhf.f\
                     zlanhp.f zlanhs.f zlanht.f zlansb.f zlansp.f zlansy.f\
                     zlantb.f zlantp.f zlantr.f zlapll.f zlapmr.f zlapmt.f\
                     zlaqgb.f zlaqge.f zlaqhb.f zlaqhe.f zlaqhp.f zlaqp2.f\
                     zlaqps.f zlaqr0.f zlaqr1.f zlaqr2.f zlaqr3.f zlaqr4.f\
                     zlaqr5.f zlaqsb.f zlaqsp.f zlaqsy.f zlar1v.f zlar2v.f\
                     zlarcm.f zlarf.f zlarfb.f zlarfg.f zlarfgp.f zlarft.f\
                     zlarfx.f zlarfy.f zlargv.f zlarnv.f zlarrv.f zlarscl2.f\
                     zlartg.f zlartv.f zlarz.f zlarzb.f zlarzt.f zlascl.f\
                     zlascl2.f zlaset.f zlasr.f zlassq.f zlaswlq.f zlaswp.f\
                     zlasyf.f zlasyf_aa.f zlasyf_rk.f zlasyf_rook.f zlat2c.f\
                     zlatbs.f zlatdf.f zlatps.f zlatrd.f zlatrs.f zlatrz.f\
                     zlatsqr.f zlauu2.f zlauum.f zpbcon.f zpbequ.f zpbrfs.f\
                     zpbstf.f zpbsv.f zpbsvx.f zpbtf2.f zpbtrf.f zpbtrs.f\
                     zpftrf.f zpftri.f zpftrs.f zpocon.f zpoequ.f zpoequb.f\
                     zporfs.f zporfsx.f zposv.f zposvx.f zposvxx.f zpotf2.f\
                     zpotrf.f zpotrf2.f zpotri.f zpotrs.f zppcon.f zppequ.f\
                     zpprfs.f zppsv.f zppsvx.f zpptrf.f zpptri.f zpptrs.f\
                     zpstf2.f zpstrf.f zptcon.f zpteqr.f zptrfs.f zptsv.f\
                     zptsvx.f zpttrf.f zpttrs.f zptts2.f zrot.f zspcon.f\
                     zspmv.f zspr.f zsprfs.f zspsv.f zspsvx.f zsptrf.f zsptri.f\
                     zsptrs.f zstedc.f zstegr.f zstein.f zstemr.f zsteqr.f\
                     zsycon.f zsycon_3.f zsycon_rook.f zsyconv.f zsyconvf.f\
                     zsyconvf_rook.f zsyequb.f zsymv.f zsyr.f zsyrfs.f\
                     zsyrfsx.f zsysv.f zsysv_aa.f zsysv_aa_2stage.f zsysv_rk.f\
                     zsysv_rook.f zsysvx.f zsysvxx.f zsyswapr.f zsytf2.f\
                     zsytf2_rk.f zsytf2_rook.f zsytrf.f zsytrf_aa.f\
                     zsytrf_aa_2stage.f zsytrf_rk.f zsytrf_rook.f zsytri.f\
                     zsytri2.f zsytri2x.f zsytri_3.f zsytri_3x.f zsytri_rook.f\
                     zsytrs.f zsytrs2.f zsytrs_3.f zsytrs_aa.f\
                     zsytrs_aa_2stage.f zsytrs_rook.f ztbcon.f ztbrfs.f\
                     ztbtrs.f ztfsm.f ztftri.f ztfttp.f ztfttr.f ztgevc.f\
                     ztgex2.f ztgexc.f ztgsen.f ztgsja.f ztgsna.f ztgsy2.f\
                     ztgsyl.f ztpcon.f ztplqt.f ztplqt2.f ztpmlqt.f ztpmqrt.f\
                     ztpqrt.f ztpqrt2.f ztprfb.f ztprfs.f ztptri.f ztptrs.f\
                     ztpttf.f ztpttr.f ztrcon.f ztrevc.f ztrevc3.f ztrexc.f\
                     ztrrfs.f ztrsen.f ztrsna.f ztrsyl.f ztrti2.f ztrtri.f\
                     ztrtrs.f ztrttf.f ztrttp.f ztzrzf.f zunbdb.f zunbdb1.f\
                     zunbdb2.f zunbdb3.f zunbdb4.f zunbdb5.f zunbdb6.f zuncsd.f\
                     zuncsd2by1.f zung2l.f zung2r.f zungbr.f zunghr.f zungl2.f\
                     zunglq.f zungql.f zungqr.f zungr2.f zungrq.f zungtr.f\
                     zunm22.f zunm2l.f zunm2r.f zunmbr.f zunmhr.f zunml2.f\
                     zunmlq.f zunmql.f zunmqr.f zunmr2.f zunmr3.f zunmrq.f\
                     zunmrz.f zunmtr.f zupgtr.f zupmtr.f 

LAPACK_COMPLEX_SRCF = iparam2stage.F zhetrd_hb2st.F 